# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
it:
  languageCode: it
  contentDir: content/it
  title: holyyeti
  params:
    description: Il sito personale di Sebastian Barzaghi, ricercatore in Digital Humanities specializzato in Linked Open Data e Open Science.
  menu:
    main:
      - name: Biografia
        url: '#about'
        weight: 10
      - name: Post
        url: '#posts'
        weight: 40
      - name: Progetti
        url: '#projects'
        weight: 30
      - name: Pubblicazioni
        url: '#featured'
        weight: 20
      - name: Contatti
        url: '#contact'
        weight: 50
  
